#ifndef _MPI_PROXY_H_
#define _MPI_PROXY_H_

/* CopyLeft Gregory Price (2017) */

#define NOT_IMPLEMENTED(op)                                         \
{                                                                   \
  if (op > MPIProxy_ERROR && op < MPIProxy_Cmd_Shutdown_Proxy)      \
    fprintf(stdout, "[%d:%s] NOT IMPLEMENTED\n", op, __FUNCTION__); \
  else                                                              \
    fprintf(stdout, "[%s] NOT IMPLEMENTED\n", __FUNCTION__);        \
  exit(EXIT_FAILURE);                                               \
}

#define NOT_IMPL(func)                            \
  EXTERNC func                                    \
  {                                               \
    NOT_IMPLEMENTED(MPIProxy_Cmd_Shutdown_Proxy); \
  }

enum MPI_Proxy_Commands
{
  MPIProxy_ERROR = 0,
  // MPI Calls
  MPIProxy_Cmd_Init = 1,
  MPIProxy_Cmd_Finalize = 2,
  MPIProxy_Cmd_Get_CommSize = 3,
  MPIProxy_Cmd_Get_CommRank = 4,
  MPIProxy_Cmd_Get_ProcessorName = 5,
  MPIProxy_Cmd_Send = 6,
  MPIProxy_Cmd_Recv = 7,
  MPIProxy_Cmd_Type_size = 8,
  MPIProxy_Cmd_Iprobe = 9,
  MPIProxy_Cmd_Get_count = 10,
  MPIProxy_Cmd_Isend = 11,
  MPIProxy_Cmd_Irecv = 12,
  MPIProxy_Cmd_Wait = 13,
  MPIProxy_Cmd_Test = 14,

  MPIProxy_Cmd_Bcast = 15,
  MPIProxy_Cmd_Abort = 16,
  MPIProxy_Cmd_Barrier = 17,
  MPIProxy_Cmd_Reduce = 18,
  MPIProxy_Cmd_Allreduce = 19,
  MPIProxy_Cmd_Alltoall = 20,
  MPIProxy_Cmd_Alltoallv = 21,
  MPIProxy_Cmd_Comm_split = 22,

  // MPIProxy_Cmd_Abort,
  MPIProxy_Cmd_Accumulate,
  MPIProxy_Cmd_Add_error_class,
  MPIProxy_Cmd_Add_error_code,
  MPIProxy_Cmd_Add_error_string,
  MPIProxy_Cmd_Address,
  MPIProxy_Cmd_Allgather,
  MPIProxy_Cmd_Iallgather,
  MPIProxy_Cmd_Allgatherv,
  MPIProxy_Cmd_Iallgatherv,
  MPIProxy_Cmd_Alloc_mem,
  // MPIProxy_Cmd_Allreduce,
  MPIProxy_Cmd_Iallreduce,
  // MPIProxy_Cmd_Alltoall,
  MPIProxy_Cmd_Ialltoall,
  // MPIProxy_Cmd_Alltoallv,
  MPIProxy_Cmd_Ialltoallv,
  MPIProxy_Cmd_Alltoallw,
  MPIProxy_Cmd_Ialltoallw,
  MPIProxy_Cmd_Attr_delete,
  MPIProxy_Cmd_Attr_get,
  MPIProxy_Cmd_Attr_put,
  // MPIProxy_Cmd_Barrier,
  MPIProxy_Cmd_Ibarrier,
  // MPIProxy_Cmd_Bcast,
  MPIProxy_Cmd_Bsend,
  MPIProxy_Cmd_Ibcast,
  MPIProxy_Cmd_Bsend_init,
  MPIProxy_Cmd_Buffer_attach,
  MPIProxy_Cmd_Buffer_detach,
  MPIProxy_Cmd_Cancel,
  MPIProxy_Cmd_Cart_coords,
  MPIProxy_Cmd_Cart_create,
  MPIProxy_Cmd_Cart_get,
  MPIProxy_Cmd_Cart_map,
  MPIProxy_Cmd_Cart_rank,
  MPIProxy_Cmd_Cart_shift,
  MPIProxy_Cmd_Cart_sub,
  MPIProxy_Cmd_Cartdim_get,
  MPIProxy_Cmd_Close_port,
  MPIProxy_Cmd_Comm_accept,
  MPIProxy_Cmd_FMPI_Comm_c2f,
  MPIProxy_Cmd_Comm_call_errhandler,
  MPIProxy_Cmd_Comm_compare,
  MPIProxy_Cmd_Comm_connect,
  MPIProxy_Cmd_Comm_create_errhandler,
  MPIProxy_Cmd_Comm_create_keyval,
  MPIProxy_Cmd_Comm_create_group,
  MPIProxy_Cmd_Comm_create,
  MPIProxy_Cmd_Comm_delete_attr,
  MPIProxy_Cmd_Comm_disconnect,
  MPIProxy_Cmd_Comm_dup,
  MPIProxy_Cmd_Comm_idup,
  MPIProxy_Cmd_Comm_dup_with_info,
  MPIProxy_Cmd_Comm_f2c,
  MPIProxy_Cmd_Comm_free_keyval,
  MPIProxy_Cmd_Comm_free,
  MPIProxy_Cmd_Comm_get_attr,
  MPIProxy_Cmd_Dist_graph_create,
  MPIProxy_Cmd_Dist_graph_create_adjacent,
  MPIProxy_Cmd_Dist_graph_neighbors,
  MPIProxy_Cmd_Dist_graph_neighbors_count,
  MPIProxy_Cmd_Comm_get_errhandler,
  MPIProxy_Cmd_Comm_get_info,
  MPIProxy_Cmd_Comm_get_name,
  MPIProxy_Cmd_Comm_get_parent,
  MPIProxy_Cmd_Comm_group,
  MPIProxy_Cmd_Comm_join,
  MPIProxy_Cmd_Comm_rank,
  MPIProxy_Cmd_Comm_remote_group,
  MPIProxy_Cmd_Comm_remote_size,
  MPIProxy_Cmd_Comm_set_attr,
  MPIProxy_Cmd_Comm_set_errhandler,
  MPIProxy_Cmd_Comm_set_info,
  MPIProxy_Cmd_Comm_set_name,
  MPIProxy_Cmd_Comm_size,
  MPIProxy_Cmd_Comm_spawn,
  MPIProxy_Cmd_Comm_spawn_multiple,
  // MPIProxy_Cmd_Comm_split,
  MPIProxy_Cmd_Comm_split_type,
  MPIProxy_Cmd_Comm_test_inter,
  MPIProxy_Cmd_Compare_and_swap,
  MPIProxy_Cmd_Dims_create,
  MPIProxy_Cmd_FMPI_Errhandler_c2f,
  MPIProxy_Cmd_Errhandler_create,
  MPIProxy_Cmd_Errhandler_f2c,
  MPIProxy_Cmd_Errhandler_free,
  MPIProxy_Cmd_Errhandler_get,
  MPIProxy_Cmd_Errhandler_set,
  MPIProxy_Cmd_Error_class,
  MPIProxy_Cmd_Error_string,
  MPIProxy_Cmd_Exscan,
  MPIProxy_Cmd_Fetch_and_op,
  MPIProxy_Cmd_Iexscan,
  MPIProxy_Cmd_FMPI_File_c2f,
  MPIProxy_Cmd_File_f2c,
  MPIProxy_Cmd_File_call_errhandler,
  MPIProxy_Cmd_File_create_errhandler,
  MPIProxy_Cmd_File_set_errhandler,
  MPIProxy_Cmd_File_get_errhandler,
  MPIProxy_Cmd_File_open,
  MPIProxy_Cmd_File_close,
  MPIProxy_Cmd_File_delete,
  MPIProxy_Cmd_File_set_size,
  MPIProxy_Cmd_File_preallocate,
  MPIProxy_Cmd_File_get_size,
  MPIProxy_Cmd_File_get_group,
  MPIProxy_Cmd_File_get_amode,
  MPIProxy_Cmd_File_set_info,
  MPIProxy_Cmd_File_get_info,
  MPIProxy_Cmd_File_set_view,
  MPIProxy_Cmd_File_get_view,
  MPIProxy_Cmd_File_read_at,
  MPIProxy_Cmd_File_read_at_all,
  MPIProxy_Cmd_File_write_at,
  MPIProxy_Cmd_File_write_at_all,
  MPIProxy_Cmd_File_iread_at,
  MPIProxy_Cmd_File_iwrite_at,
  MPIProxy_Cmd_File_iread_at_all,
  MPIProxy_Cmd_File_iwrite_at_all,
  MPIProxy_Cmd_File_read,
  MPIProxy_Cmd_File_read_all,
  MPIProxy_Cmd_File_write,
  MPIProxy_Cmd_File_write_all,
  MPIProxy_Cmd_File_iread,
  MPIProxy_Cmd_File_iwrite,
  MPIProxy_Cmd_File_iread_all,
  MPIProxy_Cmd_File_iwrite_all,
  MPIProxy_Cmd_File_seek,
  MPIProxy_Cmd_File_get_position,
  MPIProxy_Cmd_File_get_byte_offset,
  MPIProxy_Cmd_File_read_shared,
  MPIProxy_Cmd_File_write_shared,
  MPIProxy_Cmd_File_iread_shared,
  MPIProxy_Cmd_File_iwrite_shared,
  MPIProxy_Cmd_File_read_ordered,
  MPIProxy_Cmd_File_write_ordered,
  MPIProxy_Cmd_File_seek_shared,
  MPIProxy_Cmd_File_get_position_shared,
  MPIProxy_Cmd_File_read_at_all_begin,
  MPIProxy_Cmd_File_read_at_all_end,
  MPIProxy_Cmd_File_write_at_all_begin,
  MPIProxy_Cmd_File_write_at_all_end,
  MPIProxy_Cmd_File_read_all_begin,
  MPIProxy_Cmd_File_read_all_end,
  MPIProxy_Cmd_File_write_all_begin,
  MPIProxy_Cmd_File_write_all_end,
  MPIProxy_Cmd_File_read_ordered_begin,
  MPIProxy_Cmd_File_read_ordered_end,
  MPIProxy_Cmd_File_write_ordered_begin,
  MPIProxy_Cmd_File_write_ordered_end,
  MPIProxy_Cmd_File_get_type_extent,
  MPIProxy_Cmd_File_set_atomicity,
  MPIProxy_Cmd_File_get_atomicity,
  MPIProxy_Cmd_File_sync,
  // MPIProxy_Cmd_Finalize,
  MPIProxy_Cmd_Finalized,
  MPIProxy_Cmd_Free_mem,
  MPIProxy_Cmd_Gather,
  MPIProxy_Cmd_Igather,
  MPIProxy_Cmd_Gatherv,
  MPIProxy_Cmd_Igatherv,
  MPIProxy_Cmd_Get_address,
  // MPIProxy_Cmd_Get_count,
  MPIProxy_Cmd_Get_elements,
  MPIProxy_Cmd_Get_elements_x,
  MPIProxy_Cmd_Get,
  MPIProxy_Cmd_Get_accumulate,
  MPIProxy_Cmd_Get_library_version,
  MPIProxy_Cmd_Get_processor_name,
  MPIProxy_Cmd_Get_version,
  MPIProxy_Cmd_Graph_create,
  MPIProxy_Cmd_Graph_get,
  MPIProxy_Cmd_Graph_map,
  MPIProxy_Cmd_Graph_neighbors_count,
  MPIProxy_Cmd_Graph_neighbors,
  MPIProxy_Cmd_Graphdims_get,
  MPIProxy_Cmd_Grequest_complete,
  MPIProxy_Cmd_Grequest_start,
  MPIProxy_Cmd_FMPI_Group_c2f,
  MPIProxy_Cmd_Group_compare,
  MPIProxy_Cmd_Group_difference,
  MPIProxy_Cmd_Group_excl,
  MPIProxy_Cmd_Group_f2c,
  MPIProxy_Cmd_Group_free,
  MPIProxy_Cmd_Group_incl,
  MPIProxy_Cmd_Group_intersection,
  MPIProxy_Cmd_Group_range_excl,
  MPIProxy_Cmd_Group_range_incl,
  MPIProxy_Cmd_Group_rank,
  MPIProxy_Cmd_Group_size,
  MPIProxy_Cmd_Group_translate_ranks,
  MPIProxy_Cmd_Group_union,
  MPIProxy_Cmd_Ibsend,
  MPIProxy_Cmd_Improbe,
  MPIProxy_Cmd_Imrecv,
  MPIProxy_Cmd_FMPI_Info_c2f,
  MPIProxy_Cmd_Info_create,
  MPIProxy_Cmd_Info_delete,
  MPIProxy_Cmd_Info_dup,
  MPIProxy_Cmd_Info_f2c,
  MPIProxy_Cmd_Info_free,
  MPIProxy_Cmd_Info_get,
  MPIProxy_Cmd_Info_get_nkeys,
  MPIProxy_Cmd_Info_get_nthkey,
  MPIProxy_Cmd_Info_get_valuelen,
  MPIProxy_Cmd_Info_set,
  // MPIProxy_Cmd_Init,
  MPIProxy_Cmd_Initialized,
  MPIProxy_Cmd_Init_thread,
  MPIProxy_Cmd_Intercomm_create,
  MPIProxy_Cmd_Intercomm_merge,
  // MPIProxy_Cmd_Iprobe,
  // MPIProxy_Cmd_Irecv,
  MPIProxy_Cmd_Irsend,
  // MPIProxy_Cmd_Isend,
  MPIProxy_Cmd_Issend,
  MPIProxy_Cmd_Is_thread_main,
  MPIProxy_Cmd_Keyval_create,
  MPIProxy_Cmd_Keyval_free,
  MPIProxy_Cmd_Lookup_name,
  MPIProxy_Cmd_FMPI_Message_c2f,
  MPIProxy_Cmd_Message_f2c,
  MPIProxy_Cmd_Mprobe,
  MPIProxy_Cmd_Mrecv,
  MPIProxy_Cmd_Neighbor_allgather,
  MPIProxy_Cmd_Ineighbor_allgather,
  MPIProxy_Cmd_Neighbor_allgatherv,
  MPIProxy_Cmd_Ineighbor_allgatherv,
  MPIProxy_Cmd_Neighbor_alltoall,
  MPIProxy_Cmd_Ineighbor_alltoall,
  MPIProxy_Cmd_Neighbor_alltoallv,
  MPIProxy_Cmd_Ineighbor_alltoallv,
  MPIProxy_Cmd_Neighbor_alltoallw,
  MPIProxy_Cmd_Ineighbor_alltoallw,
  MPIProxy_Cmd_FMPI_Op_c2f,
  MPIProxy_Cmd_Op_commutative,
  MPIProxy_Cmd_Op_create,
  MPIProxy_Cmd_Open_port,
  MPIProxy_Cmd_Op_f2c,
  MPIProxy_Cmd_Op_free,
  MPIProxy_Cmd_Pack_external,
  MPIProxy_Cmd_Pack_external_size,
  MPIProxy_Cmd_Pack,
  MPIProxy_Cmd_Pack_size,
  MPIProxy_Cmd_Pcontrol,
  MPIProxy_Cmd_Probe,
  MPIProxy_Cmd_Publish_name,
  MPIProxy_Cmd_Put,
  MPIProxy_Cmd_Query_thread,
  MPIProxy_Cmd_Raccumulate,
  MPIProxy_Cmd_Recv_init,
  // MPIProxy_Cmd_Recv,
  // MPIProxy_Cmd_Reduce,
  MPIProxy_Cmd_Ireduce,
  MPIProxy_Cmd_Reduce_local,
  MPIProxy_Cmd_Reduce_scatter,
  MPIProxy_Cmd_Ireduce_scatter,
  MPIProxy_Cmd_Reduce_scatter_block,
  MPIProxy_Cmd_Ireduce_scatter_block,
  MPIProxy_Cmd_Register_datarep,
  MPIProxy_Cmd_FMPI_Request_c2f,
  MPIProxy_Cmd_Request_f2c,
  MPIProxy_Cmd_Request_free,
  MPIProxy_Cmd_Request_get_status,
  MPIProxy_Cmd_Rget,
  MPIProxy_Cmd_Rget_accumulate,
  MPIProxy_Cmd_Rput,
  MPIProxy_Cmd_Rsend,
  MPIProxy_Cmd_Rsend_init,
  MPIProxy_Cmd_Scan,
  MPIProxy_Cmd_Iscan,
  MPIProxy_Cmd_Scatter,
  MPIProxy_Cmd_Iscatter,
  MPIProxy_Cmd_Scatterv,
  MPIProxy_Cmd_Iscatterv,
  MPIProxy_Cmd_Send_init,
  // MPIProxy_Cmd_Send,
  MPIProxy_Cmd_Sendrecv,
  MPIProxy_Cmd_Sendrecv_replace,
  MPIProxy_Cmd_Ssend_init,
  MPIProxy_Cmd_Ssend,
  MPIProxy_Cmd_Start,
  MPIProxy_Cmd_Startall,
  MPIProxy_Cmd_Status_c2f,
  MPIProxy_Cmd_Status_f2c,
  MPIProxy_Cmd_Status_set_cancelled,
  MPIProxy_Cmd_Status_set_elements,
  MPIProxy_Cmd_Status_set_elements_x,
  MPIProxy_Cmd_Testall,
  MPIProxy_Cmd_Testany,
  // MPIProxy_Cmd_Test,
  MPIProxy_Cmd_Test_cancelled,
  MPIProxy_Cmd_Testsome,
  MPIProxy_Cmd_Topo_test,
  MPIProxy_Cmd_FMPI_Type_c2f,
  MPIProxy_Cmd_Type_commit,
  MPIProxy_Cmd_Type_contiguous,
  MPIProxy_Cmd_Type_create_darray,
  MPIProxy_Cmd_Type_create_f90_complex,
  MPIProxy_Cmd_Type_create_f90_integer,
  MPIProxy_Cmd_Type_create_f90_real,
  MPIProxy_Cmd_Type_create_hindexed_block,
  MPIProxy_Cmd_Type_create_hindexed,
  MPIProxy_Cmd_Type_create_hvector,
  MPIProxy_Cmd_Type_create_keyval,
  MPIProxy_Cmd_Type_create_indexed_block,
  MPIProxy_Cmd_Type_create_struct,
  MPIProxy_Cmd_Type_create_subarray,
  MPIProxy_Cmd_Type_create_resized,
  MPIProxy_Cmd_Type_delete_attr,
  MPIProxy_Cmd_Type_dup,
  MPIProxy_Cmd_Type_extent,
  MPIProxy_Cmd_Type_free,
  MPIProxy_Cmd_Type_free_keyval,
  MPIProxy_Cmd_Type_f2c,
  MPIProxy_Cmd_Type_get_attr,
  MPIProxy_Cmd_Type_get_contents,
  MPIProxy_Cmd_Type_get_envelope,
  MPIProxy_Cmd_Type_get_extent,
  MPIProxy_Cmd_Type_get_extent_x,
  MPIProxy_Cmd_Type_get_name,
  MPIProxy_Cmd_Type_get_true_extent,
  MPIProxy_Cmd_Type_get_true_extent_x,
  MPIProxy_Cmd_Type_hindexed,
  MPIProxy_Cmd_Type_hvector,
  MPIProxy_Cmd_Type_indexed,
  MPIProxy_Cmd_Type_lb,
  MPIProxy_Cmd_Type_match_size,
  MPIProxy_Cmd_Type_set_attr,
  MPIProxy_Cmd_Type_set_name,
  // MPIProxy_Cmd_Type_size,
  MPIProxy_Cmd_Type_size_x,
  MPIProxy_Cmd_Type_struct,
  MPIProxy_Cmd_Type_ub,
  MPIProxy_Cmd_Type_vector,
  MPIProxy_Cmd_Unpack,
  MPIProxy_Cmd_Unpublish_name,
  MPIProxy_Cmd_Unpack_external ,
  MPIProxy_Cmd_Waitall,
  MPIProxy_Cmd_Waitany,
  // MPIProxy_Cmd_Wait,
  MPIProxy_Cmd_Waitsome,
  MPIProxy_Cmd_Win_allocate,
  MPIProxy_Cmd_Win_allocate_shared,
  MPIProxy_Cmd_Win_attach,
  MPIProxy_Cmd_FMPI_Win_c2f,
  MPIProxy_Cmd_Win_call_errhandler,
  MPIProxy_Cmd_Win_complete,
  MPIProxy_Cmd_Win_create,
  MPIProxy_Cmd_Win_create_dynamic,
  MPIProxy_Cmd_Win_create_errhandler,
  MPIProxy_Cmd_Win_create_keyval,
  MPIProxy_Cmd_Win_delete_attr,
  MPIProxy_Cmd_Win_detach,
  MPIProxy_Cmd_Win_f2c,
  MPIProxy_Cmd_Win_fence,
  MPIProxy_Cmd_Win_flush,
  MPIProxy_Cmd_Win_flush_all,
  MPIProxy_Cmd_Win_flush_local,
  MPIProxy_Cmd_Win_flush_local_all,
  MPIProxy_Cmd_Win_free,
  MPIProxy_Cmd_Win_free_keyval,
  MPIProxy_Cmd_Win_get_attr,
  MPIProxy_Cmd_Win_get_errhandler,
  MPIProxy_Cmd_Win_get_group,
  MPIProxy_Cmd_Win_get_info,
  MPIProxy_Cmd_Win_get_name,
  MPIProxy_Cmd_Win_lock,
  MPIProxy_Cmd_Win_lock_all,
  MPIProxy_Cmd_Win_post,
  MPIProxy_Cmd_Win_set_attr,
  MPIProxy_Cmd_Win_set_errhandler,
  MPIProxy_Cmd_Win_set_info,
  MPIProxy_Cmd_Win_set_name,
  MPIProxy_Cmd_Win_shared_query,
  MPIProxy_Cmd_Win_start,
  MPIProxy_Cmd_Win_sync,
  MPIProxy_Cmd_Win_test,
  MPIProxy_Cmd_Win_unlock,
  MPIProxy_Cmd_Win_unlock_all,
  MPIProxy_Cmd_Win_wait,
  MPIProxy_Cmd_Wtick,
  MPIProxy_Cmd_Wtime,

  // Draining Commands
  MPIProxy_Drain_Irecv = 0x80000000,

  // Proxy Commands
  MPIProxy_Cmd_Shutdown_Proxy = 0xFFFFFFFF,
};

struct linux_dirent {
  unsigned long d_ino;        /* Inode number */
  unsigned long d_off;        /* Offset to next linux_dirent */
  unsigned short d_reclen;    /* Length of this linux_dirent */
  char d_name[];              /* Filename (null-terminated) */

  /* length is actually (d_reclen - 2 -
     offsetof(struct linux_dirent, d_name) */

  /*
     char           pad;       // Zero padding byte
     char           d_type;    // File type (only since Linux 2.6.4;
                               // offset is (d_reclen - 1))
  */
};

void mpi_proxy_wait_for_instructions();

#endif // ifndef _MPI_PROXY_H_
